name: Linux Checkup
on: [push]
jobs:

  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: docker-compose --version
      - run: echo 'job 1'
      - run: uname -a

  job-2:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'job 2'

#   Linux-Checkup:
#     runs-on: ubuntu-latest
#     steps:
#       - run: lscpu
#       - run: free -h
#       - run: df -h
#       - run: docker images
#       - run: cat /etc/os-release
#       - run: pwd
#       - run: ls
      
